In [1]:
# import necessary libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline

In [2]:
# load the dataset
df = pd.read_csv(r'C:\Users\OJO Timilehin\Downloads\Telegram Desktop/ndtv_data_final.csv', )
df.head()

,Unnamed: 0,Name,Brand,Model,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,...,Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,0,OnePlus 7T Pro McLaren Edition,OnePlus,7T Pro McLaren Edition,4085,6.67,Yes,1440,3120,8,...,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,1,Realme X2 Pro,Realme,X2 Pro,4000,6.50,Yes,1080,2400,8,...,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,2,iPhone 11 Pro Max,Apple,iPhone 11 Pro Max,3969,6.50,Yes,1242,2688,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,3,iPhone 11,Apple,iPhone 11,3110,6.10,Yes,828,1792,6,...,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,4,LG G8X ThinQ,LG,G8X ThinQ,4000,6.40,Yes,1080,2340,8,...,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990

In [3]:
df.drop(columns = ['Unnamed: 0', 'Name', 'Model'], axis = 'columns', inplace = True)

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [5]:
df.head()

,Brand,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,OnePlus,4085,6.67,Yes,1440,3120,8,12000,256.0,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,Realme,4000,6.50,Yes,1080,2400,8,6000,64.0,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,Apple,3969,6.50,Yes,1242,2688,6,4000,64.0,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,Apple,3110,6.10,Yes,828,1792,6,4000,64.0,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,LG,4000,6.40,Yes,1080,2340,8,6000,128.0,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990

In [6]:
df.isnull().sum()

Brand                     0
Battery capacity (mAh)    0
Screen size (inches)      0
Touchscreen               0
Resolution x              0
Resolution y              0
Processor                 0
RAM (MB)                  0
Internal storage (GB)     0
Rear camera               0
Front camera              0
Operating system          0
Wi-Fi                     0
Bluetooth                 0
GPS                       0
Number of SIMs            0
3G                        0
4G/ LTE                   0
Price                     0
dtype: int64

In [7]:
for cols in df.columns: 
    print(cols, ":", df[cols].nunique())

Brand : 76
Battery capacity (mAh) : 165
Screen size (inches) : 80
Touchscreen : 2
Resolution x : 28
Resolution y : 53
Processor : 6
RAM (MB) : 13
Internal storage (GB) : 15
Rear camera : 32
Front camera : 30
Operating system : 7
Wi-Fi : 2
Bluetooth : 2
GPS : 2
Number of SIMs : 3
3G : 2
4G/ LTE : 2
Price : 627

In [8]:
df.dtypes

Brand                      object
Battery capacity (mAh)      int64
Screen size (inches)      float64
Touchscreen                object
Resolution x                int64
Resolution y                int64
Processor                   int64
RAM (MB)                    int64
Internal storage (GB)     float64
Rear camera               float64
Front camera              float64
Operating system           object
Wi-Fi                      object
Bluetooth                  object
GPS                        object
Number of SIMs              int64
3G                         object
4G/ LTE                    object
Price                       int64
dtype: object

In [9]:
df.columns

Index(['Brand', 'Battery capacity (mAh)', 'Screen size (inches)',
       'Touchscreen', 'Resolution x', 'Resolution y', 'Processor', 'RAM (MB)',
       'Internal storage (GB)', 'Rear camera', 'Front camera',
       'Operating system', 'Wi-Fi', 'Bluetooth', 'GPS', 'Number of SIMs', '3G',
       '4G/ LTE', 'Price'],
      dtype='object')

 #### Categorical Variables 
 - Brand 
 - Touchscreen 
 - Operating system 
 - Wi-Fi 
 - Bluetooth 
 - GPS 
 - Number of SIMs 
 - 3G 
 - 4G/ LTE 
 
 #### Numerical Variables 
 
 - Battery capacity (mAh) 
 - Screen size (inches) 
 - Resolution x
 - Resolution y 
 - Processor 
 - RAM (MB)
 - Internal storage (GB) 
 - Rear camera 
 - Front camera 
 - Price

In [10]:
df.head()

,Brand,Battery capacity (mAh),Screen size (inches),Touchscreen,Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),Rear camera,Front camera,Operating system,Wi-Fi,Bluetooth,GPS,Number of SIMs,3G,4G/ LTE,Price
0,OnePlus,4085,6.67,Yes,1440,3120,8,12000,256.0,48.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,58998
1,Realme,4000,6.50,Yes,1080,2400,8,6000,64.0,64.0,16.0,Android,Yes,Yes,Yes,2,Yes,Yes,27999
2,Apple,3969,6.50,Yes,1242,2688,6,4000,64.0,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,106900
3,Apple,3110,6.10,Yes,828,1792,6,4000,64.0,12.0,12.0,iOS,Yes,Yes,Yes,2,Yes,Yes,62900
4,LG,4000,6.40,Yes,1080,2340,8,6000,128.0,12.0,32.0,Android,Yes,Yes,Yes,1,No,No,49990

### Brand

In [11]:
# unique values
print('Number of Unique Values: ', df.Brand.nunique()) 
print('Unique Values: ', df.Brand.unique())

Number of Unique Values:  76
Unique Values:  ['OnePlus' 'Realme' 'Apple' 'LG' 'Samsung' 'Asus' 'Xiaomi' 'Oppo' 'Huawei'
 'Google' 'Nokia' 'HTC' 'Motorola' 'Honor' 'Yu' 'Poco' 'Vivo' 'Nubia'
 'Black Shark' 'Infinix' 'Lenovo' 'Sony' 'Jio' 'Coolpad' 'Micromax'
 'Smartron' 'LeEco' 'BlackBerry' 'Gionee' 'Meizu' 'Panasonic' 'Tecno'
 'InFocus' 'Itel' '10.or' 'Lava' 'Cat' 'Lyf' 'Intex' 'Xolo' 'Acer'
 'Phicomm' 'Karbonn' 'Spice' 'iVoomi' 'Kult' 'Nuu Mobile' 'Ziox' 'Zopo'
 'ZTE' 'Onida' 'Microsoft' 'iBall' 'Mobiistar' 'Comio' 'Videocon'
 'Alcatel' 'Reach' 'Zen' 'Tambo' 'Razer' 'Homtom' 'Lephone' 'Aqua'
 'Celkon' 'Jivi' 'Billion' 'Swipe' 'M-tech' 'Sansui' 'Zuk' 'TCL' 'mPhone'
 'Blu' 'HP' 'Philips']

In [12]:
# target encode Brand with Screen size (inches) mean 
brand_screen_size = df.groupby('Brand')['Screen size (inches)'].sum().sort_values().to_dict()

In [13]:
df['Brand'] = df['Brand'].map(brand_screen_size)

In [14]:
df.Brand.nunique()

70

### Categorical dummies Varibales

In [15]:
cat_features = ['Touchscreen', 'Operating system', 'Wi-Fi', 'Bluetooth', 'GPS', 'Number of SIMs', '3G', '4G/ LTE']
df = pd.get_dummies(df, columns = cat_features , drop_first=True)

In [16]:
df.head()

,Brand,Battery capacity (mAh),Screen size (inches),Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),Rear camera,Front camera,Price,Touchscreen_Yes,Operating system_BlackBerry,Operating system_Cyanogen,Operating system_Sailfish,Operating system_Tizen,Operating system_Windows,Operating system_iOS,Wi-Fi_Yes,Bluetooth_Yes,GPS_Yes,Number of SIMs_2,Number of SIMs_3,3G_Yes,4G/ LTE_Yes
0,73.67,4085,6.67,1440,3120,8,12000,256.0,48.0,16.0,58998,1,0,0,0,0,0,0,1,1,1,1,0,1,1
1,113.97,4000,6.50,1080,2400,8,6000,64.0,64.0,16.0,27999,1,0,0,0,0,0,0,1,1,1,1,0,1,1
2,91.40,3969,6.50,1242,2688,6,4000,64.0,12.0,12.0,106900,1,0,0,0,0,0,1,1,1,1,1,0,1,1
3,91.40,3110,6.10,828,1792,6,4000,64.0,12.0,12.0,62900,1,0,0,0,0,0,1,1,1,1,1,0,1,1
4,230.36,4000,6.40,1080,2340,8,6000,128.0,12.0,32.0,49990,1,0,0,0,0,0,0,1,1,1,0,0,0,0

### Split the dataset

In [17]:
# dependent and independent features
X = df.drop('Price', axis = 'columns') 
y = df['Price']

In [18]:
#import the train_test_split 
from sklearn.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 42)

In [20]:
y_train.shape

(951,)

### Standardize the Numerical Variables

In [21]:
# import standardScaler 
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()

In [23]:
X_train

col_names= ['Brand', 'Battery capacity (mAh)', 'Screen size (inches)','Resolution x', 'Resolution y', 
                'Processor', 'RAM (MB)', 'Internal storage (GB)', 'Rear camera', 'Front camera']

In [24]:
# standardize the X_train numerical variable
X_train[col_names] = scaler.fit_transform(X_train[col_names])

<ipython-input-24-fbc0833550cc>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train[col_names] = scaler.fit_transform(X_train[col_names])
C:\Users\OJO Timilehin\anaconda3\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

In [25]:
X_train.head()

,Brand,Battery capacity (mAh),Screen size (inches),Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),Rear camera,Front camera,Touchscreen_Yes,Operating system_BlackBerry,Operating system_Cyanogen,Operating system_Sailfish,Operating system_Tizen,Operating system_Windows,Operating system_iOS,Wi-Fi_Yes,Bluetooth_Yes,GPS_Yes,Number of SIMs_2,Number of SIMs_3,3G_Yes,4G/ LTE_Yes
328,-0.386265,2.346539,1.009472,-0.347170,-0.097527,1.091245,0.889754,0.876904,0.073784,0.120253,1,0,0,0,0,0,0,1,1,1,1,0,1,1
1043,1.948888,-1.084432,-1.185701,-1.223591,-1.120176,-0.715150,-0.903224,-0.642742,-0.783632,-1.062209,1,0,0,0,0,0,0,1,1,1,1,0,1,1
318,-0.304347,0.059225,0.497265,0.967462,1.158969,1.091245,0.292095,0.008535,0.073784,0.888086,1,0,0,0,0,0,0,1,1,1,1,0,1,1
1208,0.702242,0.059225,-0.453977,-1.223591,-1.120176,-0.715150,-0.903224,-0.642742,-0.783632,-0.801146,1,0,0,0,0,0,0,1,1,1,1,0,1,0
83,-0.363477,0.631053,1.448506,0.967462,1.473093,1.091245,0.889754,0.876904,3.824981,1.963052,1,0,0,0,0,0,0,1,1,0,1,0,1,1

In [26]:
# standardize the X_test numerical variable
X_test[col_names] = scaler.fit_transform(X_test[col_names])

<ipython-input-26-fe53b3a5c582>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test[col_names] = scaler.fit_transform(X_test[col_names])
C:\Users\OJO Timilehin\anaconda3\lib\site-packages\pandas\core\indexing.py:1738: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)

In [27]:
X_test.head()

,Brand,Battery capacity (mAh),Screen size (inches),Resolution x,Resolution y,Processor,RAM (MB),Internal storage (GB),Rear camera,Front camera,Touchscreen_Yes,Operating system_BlackBerry,Operating system_Cyanogen,Operating system_Sailfish,Operating system_Tizen,Operating system_Windows,Operating system_iOS,Wi-Fi_Yes,Bluetooth_Yes,GPS_Yes,Number of SIMs_2,Number of SIMs_3,3G_Yes,4G/ LTE_Yes
51,-0.859825,-0.018186,0.395168,1.053070,0.848983,-0.686315,0.343563,0.101212,0.061964,0.066178,1,0,0,0,0,0,1,1,1,1,0,0,1,1
1100,1.886819,-0.822804,-0.386584,-0.317141,-0.382745,-0.686315,-0.265973,-0.330928,-0.441397,-0.282892,1,0,0,0,0,0,0,1,1,1,1,0,1,1
1312,1.886819,-1.052695,-0.386584,-1.230615,-1.202614,-0.686315,-1.172962,-0.546998,-0.441397,-0.806497,1,0,0,0,0,0,0,1,1,1,1,0,1,0
514,-0.818314,-0.707858,-1.168336,0.177657,-1.922405,-0.686315,-0.265973,-0.546998,-0.441397,-0.282892,1,0,0,0,0,0,0,1,1,1,1,0,1,1
1074,0.303168,-1.627422,-1.950089,-1.230615,-1.306541,-2.081748,-1.329003,-0.749240,-1.196440,-1.103207,1,0,0,0,0,0,0,1,1,0,1,0,1,0